### PR TITLE
Add support for themes to boot-codox

### PR DESCRIPTION
**Pull request by bbakersmith**

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks! Can you add an example to the example project?

**Comment by bbakersmith** [comment]
Done!

**Comment by weavejester** [comment]
Whoops, didn't notice that #155 covered this as well, otherwise I'd have merged this one first.

**Comment by bbakersmith** [comment]
You could still use the example you requested, which doesn't appear in #155 ;)

**Comment by weavejester** [comment]
Done :)

**Pull request closed without merging**
