### PR TITLE
Add support for wikilinks alternative format

### PR DESCRIPTION
**Pull request by rwilson**
Specifically `[[page|text]]`. More or less ports pegdown's behavior for this, from [here](https://github.com/sirthias/pegdown/blob/2a514555a84f56fe112155748fc24d84046e9c88/src/main/java/org/pegdown/LinkRenderer.java#L94).

Non-breaking change. Didn't bother filing an issue first since it's small.

### CODE REVIEW

**Comment by weavejester** [comment]
Can you add an example of the alternative to the example project, so it can be easily tested?

**Comment by rwilson** [comment]
Sure, example added.

**Comment by weavejester** [comment]
Thanks! It looks good. Can you squash your commits and change the commit message to:

    Add support for wikilinks [[page|text]] format

That way the subject is under 50 characters.

**Comment by rwilson** [comment]
Shit, rebase error, will fix.

**Pull request closed without merging**
