### PR TITLE
Add regexes to :include and :exclude options

### PR DESCRIPTION
**Pull request by mtnygard**
The project options :include and :exclude are now interpreted as prefixes. That is, they match their exact namespaces, and any namespaces that begin with a listed option.

For example, in project.clj

``` clojure
:codox {:include [foo.api]}
```

Would include the namespace `foo.api` as before. It will also match on `foo.api.io`, `foo.api.db`, `foo.api.db.sql`, etc.

Similarly,

``` clojure
:codox {:exclude [foo.impl foo.private]}
```

Would exclude all namespaces that match foo.impl, foo.private, or any namespace that begins with those prefixes.

This is in response to #31.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the patch, but I think we should be more explicit about whether or not a namespace is a prefix or not.

So perhaps instead, we support regular expressions in the include and exclude vectors:

```clojure
:codox {:exclude [foo.private #"^foo\.impl"]}
```

This would also allow more general use cases, like:

```clojure
:codox {:exclude [#"\.impl" #"\.internal"]}
```

You also need to be careful about the length of the summary line in your git commit message. Ideally it should be 50 characters or less, but Github wraps at 70, so anything under 70 should be fine. For example:

    Add regexes to :include and :exclude options

**Comment by mtnygard** [comment]
Good call, will revise.

**Comment by mtnygard** [comment]
Include and exclude now act as requested:

* A symbol is matched exactly.
* A regex is matched anywhere in the namespace name.

**Comment by weavejester** [comment]
Thanks for the patch. I have a few suggestions about the code.

`symbol-set` was public because it was fairly generic, but we can dispense with that and make the replacement function private.

Since we don't have any plans to add more syntax to include/exclude, rather than using a multimethod, a private `cond` should be used instead. I'd rather not have polymorphism for things that we're not sure should be public.

```clojure
(defn- ns-matches? [pattern {ns-name :name}]
  (cond
    (instance? Pattern pattern) (re-find pattern (str ns-name))
    (string? pattern) (= pattern (str ns-name))
    (symbol? pattern) (= pattern (symbol ns-name))))
```

Rather than write a function that returns a matcher function, it might be simpler just to write the function directly. For example:

```clojure
(defn- ns-matches-any? [patterns ns]
  (some (fn [pattern] (ns-matches pattern ns))
        (if (coll? patterns) patterns [patterns])))
```

**Comment by mtnygard** [comment]
Please see latest commit. That includes the simplifications you identified.

**Comment by weavejester** [comment]
This seems fine. Can you squash your commits?

**Comment by mtnygard** [comment]
Squashed.

**Comment by weavejester** [comment]
Perfect, thanks!

**Pull request merged**
